codecov:
  branch: develop
  bot: kirkcola
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        threshold: 0.1

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes  # [yes :: must have a head report to post]
