### Buidling static files ###
FROM node:10.18-alpine as builder
WORKDIR /usr/app/

# Install dependencies
COPY package.json ./
RUN yarn install

# Copy source files
COPY ./ ./

# Buiding
CMD ["npm", "run", "build:prod"]

### Deploy to nginx ###
FROM nginx:alpine
COPY .docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/app/dist /usr/share/nginx/html
