export default {
  'loading.forminst.getform': 'Fetching form',
  'loading.forminst.getforminfo': 'Fetching form details',
  'loading.forminst.getFormdata': 'Fetching form data',

  'forminst.common.inputable.placeholder': 'Please input here',
  'forminst.common.selectable.placeholder': 'Please select',
  'forminst.common.create': 'Create',
  'forminst.common.gen-by-sys': 'Generated by system',
  'forminst.schema.input': 'Input',
  'forminst.schema.textarea': 'Text Area',
  'forminst.schema.date': 'Date',
  'forminst.schema.date.placeholder': 'Year-Month-Day',
  'forminst.schema.number': 'Number',
  'forminst.schema.radio': 'Radio',
  'forminst.schema.checkbox': 'Checkbox',
  'forminst.schema.select': 'Select',
  'forminst.schema.switch': 'Switch',
  'forminst.schema.sn': 'Serial No.',
  'forminst.schema.creator': 'Creator',
  'forminst.schema.modify-time': 'Modified Time',
  'forminst.schema.create-time': 'Created Time',
  'forminst.schema.assoc-form': 'Associated Form',
  'forminst.schema.assoc-prop': 'Associated Property',
  'forminst.schema.assoc-mult-form': 'Multi-Select AForm ',

  'forminst.schema.switch.yes': 'Yes',
  'forminst.schema.switch.no': 'No',

  'forminst.assoc-form-modal.title': 'Select association form',

  'forminst.schema.input.nomal.message': 'Text must be less than {count} characters',
  'forminst.schema.input.email.message': 'Please fill in the correct email format',
  'forminst.schema.input.idcard.message': 'Please fill in the correct ID number',
  'forminst.schema.input.phone.message': 'Please fill in the correct phone number',

  'forminst.schema.owner.nomember': 'No staff',
  'forminst.schema.owner.mydept': 'My department',
  'forminst.schema.owner.message': 'Please fill in the owner',

  'forminst.schema.ownerdept.message': 'Please fill in the department',

  // 子表
  'forminst.schema.subform.number': 'No.',
  'forminst.schema.subform.opts': 'Opts',
  'forminst.schema.subform.opts.copy': 'Copy',
  'forminst.schema.subform.opts.reset': 'Reset the current row',
  'forminst.schema.subform.opts.insert-before': 'Insert a row above',
  'forminst.schema.subform.opts.insert-after': 'Insert a row below',

  // 列表查询
  'forminst.query.queryitems': 'Query items',
  'forminst.query.date.today': 'Today',
  'forminst.query.date.yesterday': 'Yesterday',
  'forminst.query.date.thisweek': 'This Week',
  'forminst.query.date.thismonth': 'This month',
  'forminst.query.date.lastmonth': 'Last month',
  'forminst.query.date.thisquarter': 'This quarter',
  'forminst.query.date.thisyear': 'This year',
};
