export const API_PATH = '/api';

/**
 *
 * `[ACTION]`: `[METHOD] /path/to/{param}/app`
 */
export const API = {
  global: {
    HEALTH_CHECK: 'GET /health-check',
  },
  account: {
    REGISTER: 'POST /user/register',
    REGISTER_SEND_CODE: 'GET /user/register-auth-code',
    RESET_PASSWORD: 'PUT /user/reset-password',
    RESETPASSWD_SEND_CODE: 'GET /user/reset-password-auth-code',
    RESETPASSWD_CHECK_CODE: 'GET /user/check-reset-password-auth-code',
    LOGIN: 'POST /user/login',
    REDEEM_TOKEN: 'GET /user/member-info',
    CHECK_EMAIL: 'GET /user/check-email',
    GET_JOINED_ORGS: 'GET /user/{id}/join-companys',
    SWITCH_ORG: 'PUT /user/{id}/current-company',
    RESET_TO_NO_ORG: 'PUT /user/{id}/empty-company',
    DELETE: 'DELETE /user/{id}',
  },
  app: {
    CREATE: 'POST /app',
    GET: 'GET /app/{appId}',
    GET_FORMTPL_LIST: 'GET /app/{appId}/form-templates',
    UPDATE: 'PUT /app/{appId}',
    DELETE: 'DELETE /app/{appId}',
  },
  organization: {
    APP_LIST: 'GET /company/{orgId}/apps',
    ASSOC_FORMS: 'GET /company/{orgId}/association-forms',
    LINK_FORMS: 'GET /company/{orgId}/linked-target-forms',
    CREATE: 'POST /company',
    DELETE: 'DELETE /company/{orgId}',
    GET: 'GET /company/{orgId}',
    DISSOLVE_ORG_SURVEY: 'POST /log-record/dissolve-company-reason',
  },
  department: {
    GET_DEPARTMENTS: 'GET /company/{id}/departments',
    CREATE: 'POST /department',
    UPDATE: 'PUT /department/{id}',
    DELETE: 'DELETE /department/{id}',
    UPDATE_MANAGER: 'PUT /department/{id}/manager',
    DEPTS_TREE: 'POST /department/dept-chain',
  },
  role: {
    GET_ROLES: 'GET /company/{id}/roles',
    GREAT: 'POST /role',
    DELETE: 'DELETE /role/{id}',
    UPDATE: 'PUT /role/{id}/name',
    GET_ROLE_MEMBERS: 'GET /role/{id}/members',
    UPDATE_ROLE_MEMBERS: 'PUT /role/{id}/members',
    DELETE_ROLE_MEMBER: 'DELETE /role/{id}/members',
    GET_SUBADMIN: 'GET /role/{id}/subadmin-roles',
    CREATE_SUBADMIN: 'POST /role/{id}/subadmin-role',
    UPDATE_SUBADMIN: 'PUT /role/{id}/subadmin-role/{subAdminRoleId}',
    DELETE_SUBADMIN: 'DELETE /role/{id}/subadmin-role/{subAdminRoleId}',

    GET_APP_ACLS: 'GET /company/{orgId}/role/{roleId}/app-acls',
    GET_FORM_ACLS: 'GET /app/{appId}/role/{roleId}/form-acls',
    SAVE_FORM_ACLS: 'PUT /role/{id}/role-acl',
  },
  member: {
    GET_ORG_MEMBERS: 'GET /company/{id}/members',
    GET_DEPT_MEMBERS: 'GET /department/{id}/members',
    INFO: 'GET /member/{id}',
    INVITE: 'POST /member',
    INVITE_AGAIN: 'PUT /member/re-invite-member',
    UPDATE: 'PUT /member/{id}',
    DELETE: 'DELETE /member',
    ADJUST: 'PUT /member/departments',
    ACCEPT_INVITATION: 'GET /member/accept',
  },
  formTemplate: {
    CREATE: 'POST /form-template',
    GET: 'GET /form-template/{formId}',
    UPDATE: 'PUT /form-template/{formId}',
    DELETE: 'DELETE /form-template/{formId}',
    CONTROL_CODE: 'POST /form-template/control-code',
    DB_FIELDS: 'GET /form-template/db-name/{formCode}/db-fields',
    GET_RECORD_LIST_SETTINGS: 'GET /form-template/{formTplId}/list-view-setting',
    UPDATE_RECORD_LIST_SETTINGS: 'PUT /form-template/{formTplId}/list-view-setting',
    UPDATE_FORM_NAME: 'PUT /form-template/{formTplId}/name',
  },
  formRecord: {
    GET_FORM_TO_FILLIN: 'GET /formdata/{formTemplateCode}/create',
    GET_FORM_TO_EXAMINE: 'GET /formdata/{formTemplateCode}/{objectId}/info',
    GET_FORM_TO_UPDATE: 'GET /formdata/{formTemplateCode}/{objectId}/edit',
    SUBMIT_FORM: 'POST /formdata',
    UPDATE_FORM_RECORD: 'PUT /formdata/{objectId}',
    DELETE_FORM_RECORD: 'DELETE /formdata/{objectId}',
    SAVE_FORM_AS_DRAFT: 'POST /formdata/temporary-storage',
    UPDATE_FORM_DRAFT: 'PUT /formdata/temporary-storage/{objectId}',
    GET_HEADERS: 'GET /formData/header',
    GET_LIST: 'POST /formData/list',
    GET_SELECT_SOURCE: 'GET /formData/{formTemplateCode}/schema-property-values',
    GET_DATALINK_SOURCE: 'POST /formData/{formTemplateCode}/data-link-data',
    GET_ASSOC_FORM_DATA: 'GET /formData/{formTemplateCode}/association-form-datas',
    GET_ASSOC_PROPERTY: 'GET /formData/{formTemplateCode}/{objectId}/association-property',
    GET_QUERY_ITEMS: 'GET /formData/query-items',
    DELETE_FORM_RECORD_BULK: 'DELETE /formData',
  },
};
