version: '3.5'

services:
  lcp_dev:
    ports:
      - 80:80
    build:
      context: ../
      dockerfile: Dockerfile.dev
    container_name: 'lcp_dev'
    volumes:
      - ../src:/usr/src/app/src
